### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by se16n** [mattseemon/todo.txt-WPF#7]

**Comment by se16n** [comment]
Found this http://projects.mattseemon.in/todo.txt/releases/TodotxtPortable.zip

But now i have one more question: can run under .NET framework > 4.6? 4.5.1 for example?

**Comment by mattseemon** [comment]
Hey @se16n ,

I am still working on adding some tweaks to it. :) But you can download the the latest build from

http://projects.mattseemon.in/todo.txt/releases/Setup.exe
The Portable Version still has some auto update issues, I am trying to work it. I expect to publish Version 1. in the next couple of weeks. Until then you can install the latest Beta from the above location.

I have been building using .NET Framework 4.6. But I dont see why it should not work on 4.5.1. I know it probably wont work with versions below 4.5.1, due to a few nuget packages that require 4.5.1.

-Matt.

**Comment by mattseemon** [comment]
Released Version 1.0.0. It is available in the Releases Section. The Website for the same will be up and about in a couple of weeks.
